// <auto-generated />
using System;
using Dz.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dz.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221017172620_addSeedData")]
    partial class addSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dz.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2022, 10, 18, 0, 26, 20, 645, DateTimeKind.Local).AddTicks(2134),
                            Category = 1,
                            FirstName = "Nguyen",
                            LastName = "Dzung",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2022, 10, 18, 0, 26, 20, 645, DateTimeKind.Local).AddTicks(2150),
                            Category = 1,
                            FirstName = "Thao",
                            LastName = "Nam",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
